# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux 
files:
  - source: client-mobile
    destination: /var/www/html/client-mobile
  - source: client-screen
    destination: /var/www/html/client-screen
  - server: server
    destination: /opt/deco-server