version: 0.2
# AWS Code build definition that builds all node projects inside of this repository.
env:
    shell: bash
phases:
    install:
      runtime-versions:
        nodejs: 12
      commands:
        - echo Install phase started on `date`
    pre_build:
      commands:
        - echo Pre-build started on `date`
        - cd $CODEBUILD_SRC_DIR
        - yarn install
    build:
      commands:
        - echo Build started on `date`
        - cd $CODEBUILD_SRC_DIR
        - yarn --cwd ./packages/common-types/ build
        - yarn --cwd ./packages/common-utils/ build
        - yarn --cwd ./packages/server/ build
        - yarn --cwd ./packages/client-mobile/ build
        - yarn --cwd ./packages/client-screen/ build
    post_build:
        commands:
          - echo Build $CODEBUILD_BUILD_NUMBER completed on `date`
          - aws s3 ls s3://deco7381-build-artifacts/
artifacts:
  files:
    - ./packages/client-mobile/build/**/*
    - ./packages/client-screen/build/**/*
    - ./packages/server/dist/**/*
  discard-paths: no