version: 0.2
# AWS Code build definition that builds all node projects inside of this repository.
env:
    shell: bash
phases:
    install:
      runtime-versions:
        nodejs: 12
      commands:
        - echo Install phase started on `date`
    pre_build:
      commands:
        - echo Pre-build started on `date`
        - cd $CODEBUILD_SRC_DIR
        - yarn install
    build:
      commands:
        - echo Build started on `date`
        - cd $CODEBUILD_SRC_DIR
        - yarn --cwd ./packages/common-types/ build
        - yarn --cwd ./packages/common-utils/ build
        - yarn --cwd ./packages/server/ build
        - yarn --cwd ./packages/client-mobile/ build
        - yarn --cwd ./packages/client-screen/ build
    post_build:
        commands:
          - echo Packaging started on `date`
          - cd $CODEBUILD_SRC_DIR
          - mkdir -p ./bin
          - cp ./appspec.yml ./bin/
          - mkdir ./bin/client-mobile
          - cp -R ./packages/client-mobile/build/* ./bin/client-mobile/
          - mkdir -p ./bin/client-screen
          - cp -R ./packages/client-screen/build/* ./bin/client-screen/
          - mkdir -p ./bin/server
          - cp -R ./packages/server/dist/* ./bin/server/
          - cd $CODEBUILD_SRC_DIR/bin
          - tar -cvzf ../deco7381.tar.gzip .
          - echo Build $CODEBUILD_BUILD_NUMBER completed on `date`
artifacts:
  files:
    - ./deco7381.tar.gzip
  discard-paths: no